### PR TITLE
Pixel scale blurring fix

### LINKED ISSUE #173: Aspect ratio affects the horizontal aliasing/blur
**Describe the bug**
Using a very low width/height ratio results in a blurry image. And a very high ratio leads to aliasing.

I have a strong suspicion that PixelScale isn't set to the right value in the vertex shader of most cameras.

**To Reproduce**
1. Select an example, 2D or 3D
2. Give the preview a small width
3. A horizontal blur appears

**Expected behavior**
I would expect it not to blur/create aliasing.

**Screenshots**
Here's a 512x512 3D render, cropped to 512x64
blur-2-crop
And here's the exact same scene rendered at 512x64, a blur is visible.
blur-1
Here's the same thing but 2D:
blur-3-crop
blur-4

**Desktop (please complete the following information):**
 - OS: Win10
 - Gfx card: nVidia GTX 980
 - Driver version: nVidia 461.92

### PR DESCRIPTION
**Pull request by loicvdb**
Fixed https://github.com/3Dickulus/FragM/issues/173.

### CODE REVIEW

**Comment by 3Dickulus** [comment]
just studying this a bit now... this is something that has been there from the beginning.

have you done any testing ?

**Comment by 3Dickulus** [comment]
what, if any, impact does this have when using devicePixelRatio()? used when calculating DisplayWidget::pixelWidth() and DisplayWidget::pixelHeight(), 1 for most systems 2 for retina display and varying between phone, tablet and desktop displays.

Does FragM even need to use devicePixelRatio()? it is not intended for phones or tablets (or labtops really) 99% GPU usage for extended periods on these devices tends to cook them quickly. This might trigger some code cleanup, can probably dump some redundant bits.

will merge, would like to hear your input.

**Comment by loicvdb** [comment]
> 
> 
> just studying this a bit now... this is something that has been there from the beginning.
> 
> have you done any testing ?

I've tested examples using 2D.frag and 3D.frag, the other cameras use the same vertex shaders so it should be fine.

> 
> 
> what, if any, impact does this have when using devicePixelRatio()? used when calculating DisplayWidget::pixelWidth() and DisplayWidget::pixelHeight(), 1 for most systems 2 for retina display and varying between phone, tablet and desktop displays.
> 
> Does FragM even need to use devicePixelRatio()? it is not intended for phones or tablets (or labtops really) 99% GPU usage for extended periods on these devices tends to cook them quickly. This might trigger some code cleanup, can probably dump some redundant bits.
> 
> will merge, would like to hear your input.

I'm not yet that familiar with Qt, but I see that `devicePixelRatio()` has to do with the scale of the pixels on the physical display compared to "device-independent pixels". If width() and height() are the actual dimensions of the image being rendered only this should matter. If `devicePixelRatio()` alters the final image depending on the device it's rendered on then yeah you should definitely get rid of it. Also I agree that support for phones/tablets isn't really a priority, given that FragM requires quite a bit of GPU power.

**Comment by 3Dickulus** [comment]
yes, devicePixelRatio() is for QDesktopWidget ie: the primary widget that is the desktop screen, it has to know devicePixelRatio, but I think a widget in a window on the desktop should be fine with inheriting that info. tried running FragM at different desktop zoom settings 100% 150% 200% (devicePixelRatios) and find that it doesn't affect the GL area, only the text and widget layouts.
I have removed the associated code.

**Pull request merged**
